import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import 'balloon/styles/globals.css'
import 'balloon/styles/footer.css'
import 'balloon/styles/Home.css'
import 'balloon/styles/search.css'
import 'balloon/styles/product.css'
import 'balloon/styles/trackOrder.css'
import 'balloon/styles/header.css'
import type { AppProps } from 'next/app'
import Header from '../components/Header/Header'
import SecondHeader from 'balloon/components/SecondHeader/SecondHeader'
import Footer from 'balloon/components/Footer/Footer'

export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header></Header>
    <SecondHeader></SecondHeader>
    <Component {...pageProps} />
    <Footer></Footer>
  </>
}
